# Generated by Django 5.2.7 on 2025-10-24 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="developer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_cpu",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_gpu",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_ram",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="release_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pcsetup",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pcsetup",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="GamePerformanceDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("gpu", models.CharField(max_length=100)),
                ("ram", models.IntegerField()),
                ("storage_type", models.CharField(max_length=50)),
                ("fps", models.FloatField()),
                ("cpu_usage", models.FloatField()),
                ("gpu_usage", models.FloatField()),
                ("temperature", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_fps", models.FloatField()),
                ("predicted_cpu_usage", models.FloatField()),
                ("predicted_gpu_usage", models.FloatField()),
                ("predicted_temperature", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pcsetup"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedback",
            name="prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.prediction",
            ),
        ),
    ]
