# Generated by Django 5.2.7 on 2025-10-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_feedback_comments_game_developer_game_min_cpu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cores", models.IntegerField()),
                ("threads", models.IntegerField()),
                ("base_clock", models.FloatField()),
                ("boost_clock", models.FloatField()),
                ("tdp", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vram", models.IntegerField()),
                ("base_clock", models.FloatField()),
                ("boost_clock", models.FloatField()),
                ("tdp", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("chipset", models.CharField(max_length=100)),
                ("form_factor", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("wattage", models.IntegerField()),
                ("efficiency_rating", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="gameperformancedataset",
            name="game",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="game",
        ),
        migrations.RemoveField(
            model_name="pcsetup",
            name="user",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="setup",
        ),
        migrations.CreateModel(
            name="ComputerBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.cpu"
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.gpu"
                    ),
                ),
                (
                    "motherboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.motherboard",
                    ),
                ),
                (
                    "power_supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.powersupply",
                    ),
                ),
                (
                    "ram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ram"
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.storage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=100)),
                ("average_fps", models.FloatField()),
                ("resolution", models.CharField(max_length=50)),
                ("settings", models.CharField(max_length=100)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.computerbuild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_usage", models.FloatField()),
                ("gpu_usage", models.FloatField()),
                ("ram_usage", models.FloatField()),
                ("temperature", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.computerbuild",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="GamePerformanceDataset",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="PCSetup",
        ),
        migrations.DeleteModel(
            name="Prediction",
        ),
    ]
