# Generated by Django 5.2.7 on 2025-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_cpu_gpu_motherboard_powersupply_ram_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_id",
        ),
    ]
